### PR TITLE
Issue-537: Add button to load language settings from the cloud

### LINKED ISSUE #537: Add button to load language settings into WordPress from the cloud
Sometimes the language code and alphabet are not being set during upload

### PR DESCRIPTION
**Pull request by phillip-hopper**
Resolves #537

### CODE REVIEW

**Comment by vernastutzman** [comment]
Where should I look for the button, @phillip-hopper

**Comment by phillip-hopper** [comment]
image

**Comment by vernastutzman** [comment]
Here is a picture of the Browse view settings on https://www.webonary.work/test-stutzman6/wp-admin/admin.php?page=webonary#browse before clicking the Refresh Settings From Cloud Data:
image

Here is a picture of it after clicking the Refresh... button:
image

Something isn't right!!!

**Comment by vernastutzman** [comment]
This is on https://www.webonary.work/test-stutzman5/ before the button was clicked:
image

Same site, after the button is clicked:
image

Seems like it always reverts to the French Sample Database.

**Comment by phillip-hopper** [comment]
@vernastutzman  After digging into the MongoDB data, it looks like the results are correct after you click the button. The discrepancy is probably because the Wordpress data is updated daily but the Cloud data is not. I recommend uploading to .work, then test the button.

**Pull request merged**
