### PR TITLE
Update the package-lock.json file

### PR DESCRIPTION
**Pull request by johntseng**
This was automatically updated by running `npm install`. Lockfiles from npm v6 are automatically updated when a newer version of npm is used. See https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json#handling-old-lockfiles

### CODE REVIEW

**Comment by johntseng** [comment]
Hi, 

I would like to contribute to SIL, and Steven said the Webonary Cloud API is a good place to start. I'm not sure what the process here is. I'm just sending over a trivial pull request to get the ball rolling.

**Comment by phillip-hopper** [comment]
@johntseng what version of node are you using?

**Comment by johntseng** [comment]
I'm using node 16.14.2 with npm 8.5.5.

**Comment by phillip-hopper** [comment]
@johntseng I've been told that node 12.4.0 is the required version for AWS Lambda.

**Pull request closed without merging**
